### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by nmonastyrskyi**

### CODE REVIEW

**Comment by cswenor** [comment]
The social links for all the people are still not linked appropriately.
The bottom telegram link isn't linked appropriately.
You have a test link still in popups.
There is a weird image jump when you click on the popups for the advisors.
The Blog Link isn't pointed at https://medium.com/alacris
Also please use this tracking code: UA-126531474-1
And this link for the Contact Form at the top and bottom: https://alacris.typeform.com/to/x06duY

**Review by cswenor — CHANGES_REQUESTED** [review]
I left a comment on the PR, please make these changes and resubmit.

**Comment by nmonastyrskyi** [comment]
> The social links for all the people are still not linked appropriately.
> The bottom telegram link isn't linked appropriately.
  -added
> You have a test link still in popups.
 -removed
> There is a weird image jump when you click on the popups for the advisors.
-Fixed this bu by  adding cached images of advisors(It was happening because images started loading, when popup was opened)
> The Blog Link isn't pointed at https://medium.com/alacris
-pointed
> Also please use this tracking code: UA-126531474-1
-Already is using
> And this link for the Contact Form at the top and bottom: https://alacris.typeform.com/to/x06duY
-added

**Comment by cswenor** [comment]
The links in the popup should line up with the social links on the left.

Then I believe we are done.

**Comment by nmonastyrskyi** [comment]
> The links in the popup should line up with the social links on the left.
> 
> Then I believe we are done.

Done

**Review by cswenor — APPROVED** [review]

**Pull request merged**
